### ISSUE TITLE
ionide does not find assembly

### ISSUE THREAD

**Issue by vrescobar** [fsprojects/SwaggerProvider#149] opened 2020-05-04 17:55 UTC
### Description

I followed the [documentation](http://fsprojects.github.io/SwaggerProvider/#/) to create the PetStore example on a console application. The only difference is that I used the newest version 0.10.2 rather than 0.10.0

But the issue is present with both of them.

### Repro steps

dotnet new console --name apiclient --language F#
cd apiclient
dotnet add package SwaggerProvider

copy the example code from the docs into Program.fs

### Expected behavior

The program compiles and ionide autocompletes as expected.

### Actual behavior

The program compiles and works as expected but ionaide on vscode for mac complains with the following errors:

`
The type provider '~/.nuget/packages/swaggerprovider/0.10.2/lib/netstandard2.0/SwaggerProvider.Runtime.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'SwaggerProvider.DesignTime.dll' which cannot be loaded or doesn't exist. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
`

And also:

```{
	"resource": "~/projects/apiclient/Program.fs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "3005",
	"severity": 4,
	"message": "Referenced assembly ~/.nuget/packages/swaggerprovider/0.10.0/lib/netstandard2.0/SwaggerProvider.Runtime.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found",
	"source": "F# Compiler",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

Cleaning the cache and recompiling doesn't help.

### Known workarounds

None yet

### Related information 

* Mac OS
* Newest latest Visual Studio Code and  Ionide-fsharp
* Version `<PackageReference Include="SwaggerProvider" Version="0.10.2" />`
* `<TargetFramework>netcoreapp3.1</TargetFramework>`
* Doc followed: http://fsprojects.github.io/SwaggerProvider/#/

**Comment by sergey-tihon** [comment] 2020-05-04 17:57
This is duplicate of https://github.com/fsprojects/SwaggerProvider/issues/147
TypeProviders does not work in latest Ionide

**Closed** 2020-05-08 17:44 UTC
