### ISSUE TITLE
Error when using with Xamarin

### ISSUE THREAD

**Issue by Lenne231** [fsprojects/SwaggerProvider#54] opened 2016-10-08 12:28 UTC
### Description

I get the following error when i try to install the package in a Xamarin Android project. Is there a way to enable SwaggerProvider for Xamarin/Mono?

![image](https://cloud.githubusercontent.com/assets/2046557/19213132/4dfcc620-8d63-11e6-81e1-d30d54ac79d0.png)
### Repro steps
1.  Create a Xamarin Android project in Visual Studio
2.  Try to install the package (v0.5.6)

**Comment by sergey-tihon** [comment] 2016-10-09 09:04
It should work on Mono (at least everything is OK on travis-ci), but Xamarin ...

What profile should I target to support Xamarin/Mono? 
Still some PCL or NetStandard already works?
// @tpetricek @ovatsus @pezipink @enricosada - appreciate any suggestions

**Comment by sergey-tihon** [comment] 2016-10-09 09:18
More general question is how to create generative type provider that support ([F# 3.0](https://github.com/fsprojects/SwaggerProvider/issues/42), F# 3.1, F# 4.0) and as much platforms as possible?

**Comment by nosami** [comment] 2016-10-09 18:53
Maybe this helps https://github.com/xamarin/Xamarin.Android.FSharp.ResourceProvider . It's a type provider I wrote for Android a couple of weeks ago. The Android specific stuff is in the Android folder.

**Comment by Lenne231** [comment] 2016-10-11 16:58
Tried several PCL profiles, none of them works, always the same error. `Profile47` seems to have a problem with YamlDotNet.

![image](https://cloud.githubusercontent.com/assets/2046557/19280119/abd05964-8fe4-11e6-93af-5250e149afc5.png)

**Comment by laygr** [comment] 2016-10-26 19:47
PCL should be the way to go for supporting most platforms (id est, the most restrictive platform in terms of dependencies). I recommend profile 259, which supports: .NET Framework 4.5,   Windows 8, Windows Phone 8.1, Windows Phone Silverlight 8 and Xamarin.iOS, Xamarin.Android. Xamarin.etc
src: http://danrigby.com/2014/05/14/supported-pcl-profiles-xamarin-for-visual-studio-2/

(very nice library!)

**Comment by willsam100** [comment] 2017-03-09 21:17
What's the status of this?
I tried this with Xamarin Forms and had the same problem. As @nosami said, a PCL would be the way to go. I can confirm this does work on mono targeting .NET 4.5 i.e running on the mac. 
Having swaggerProvider support iOS and Android (as well as the PCL for Xamarin Forms, if that is possible), would be a great win for F# in the mobile space. 
Happy to help out in any way that I can.

**Comment by sergey-tihon** [comment] 2017-03-10 06:03
Yes, I does not work for iOS, Android and PCL now.
I do not know of any `generative` TP that works on PCL... Probably we should convert SwaggerProvider to erased type provider and do not generate real types...

The easiest way (as it looks for me now) is to wait for .NET Standards 2.0 when we will be able to compile TP for .NET Standard and deliver them to all platforms.

>I can confirm this does work on mono targeting .NET 4.5 i.e running on the mac
There is at least two reasons why it should work on mono
- `Travis CI` tests are green 
- I compile it from VS Code on MacOS now =)

**Comment by enricosada** [comment] 2017-03-12 15:43
> The easiest way (as it looks for me now) is to wait for .NET Standards 2.0 when we will be able to compile TP for .NET Standard and deliver them to all platforms

well, see https://github.com/Microsoft/visualfsharp/issues/2400#issuecomment-279028891 for info about generative TP and netstandard 2.0. maybe generative are not goin to be in, or will need some changes.. @sergey-tihon if interested about that, join discussion please

**Comment by sergey-tihon** [comment] 2017-03-13 07:42
@enricosada  thank you for pointing me to this discussion.
Link this discussion with related issue https://github.com/Microsoft/visualfsharp/issues/2406#issuecomment-286034837

**Comment by 7sharp9** [comment] 2017-03-14 15:40
Generative providers work just fine if you make outputs available for both droid and iOS.

**Comment by migueldeicaza** [comment] 2017-03-14 15:41
You do not need a PCL for xamarin, you could use bait and switch (which nugetizer 3000 makes easy).  That way you have an API "contract" that is PCL or Netstandard and limited by those and you have a full android/iOS implementations that use the full API.

**Comment by 7sharp9** [comment] 2017-03-14 15:53
From memory `Http.fs` is from Hopac which will have some thread usage scenarios not implemented by iOS/droid, so that will need a patch too.

**Comment by sergey-tihon** [comment] 2017-03-28 20:35
Before I publish new version of SwaggerProvider, I would love hear feedback from PCL, Xamarin & TP experts about the design (and possible pitfalls): @7sharp9 @nosami @mavnn @cartermp @dsyme 

### Description
SwaggerProvider is `generative` type provider and I would like to keep `generative` because it will allow to use type provided by TP in C# project. This scenario is particularly important for Xamarin applications.

TP implemented as 3 assemblies (as described in [RProvider Developer Notes](http://bluemountaincapital.github.io/FSharpRProvider/devnotes.html))
- `SwaggerProvider.dll` - contains only `TypeProviderAssembly` attribute
- `SwaggerProvider.Runtime.dll` - contains code used in runtime by `emitted` methods. This assembly depend on `JSON.NET` because TP need to serialize/deserialize payload for requests.
- `SwaggerProvider.Design.dll` - contains all TP code and depends on `YamlDotNet` that is needed to parse Swagger schemas in `Yaml` (note that `YamlDotNet` is not PCL friendly, but I do not need this assembly in runtime)

### Motivation
I do not want to compile assemblies for each target runtime and pack multiple binaries in one NuGet package (if this is possible)

### Approach
- Compile `SwaggerProvider.dll` & `SwaggerProvider.Runtime.dll` for `PCL` (`Profile259`)
- Compile `SwaggerProvider.Design.dll` for `net45` and use  `YamlDotNet` as is
- Put all 4 assemblies directly in `/lib/` folder (without runtime subfolders)
- On `NuGet` package level specify that only 2 `PCL` assemblies should be added to `.fsproj` file.
- NuGet package will depend only on `JSON.NET`

### Questions
1. What is wrong with described approach? (From your experience view-point)
1. How to allow consumers to use arbitrary version of `FSharp.Core.dll`? (As I understand new `The ProvidedTypes API` is only for erasing TP)
1. I faced an error in VS2015 `FSC : error FS2024: Static linking may not use assembly that targets different profile.` that was fixed in VS2017 https://github.com/Microsoft/visualfsharp/issues/99/ Does it mean that users of older version of VS may not be able to compile projects with SwaggerProvider?
1. Are there any other `generative` TP that already work everywhere?

Thanks everybody for replies

**Comment by 7sharp9** [comment] 2017-03-28 21:14
1. Sounds sensible, although compiling per platform would be necessary if certain portions of code need to be changed for those platforms.

2. Tricky if compiled once as the Fsharp.Core in the provider 259 would need to match that of the consumers project.

3. No idea, I don't use VS.

4. Yes is 1. is not an issue

5.  I have one that targets 3 different reference assemblies but they all use the same Fsharp.Core.  I do compiler 3 different TP's though.

**Comment by 7sharp9** [comment] 2017-03-28 22:28
I just tried with iOS just to see and got the following error:

```
{System.TypeLoadException: Failure has occurred while loading a type.   at Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized (System.Reflection.Assembly fsharpCoreAssembly) [0x00048] in <607e95f78559498690f968784b884761>:0    at Newtonsoft.Json.Serializat…}
```

On accessing:
```
petStore.GetInventory()
```

**Comment by dsyme** [comment] 2017-03-30 18:41
> What is wrong with described approach? (From your experience view-point)

I don't immediately spot any specific problem.  However cross-targetinng type providers are hard to get right and test. We will need to put a lot more effort into this.  This is a good starting point - since your Profile259-executing type providers will also be usable with both .NET Core and .NET Framework versions of the F# compiler.

I wasn't actually aware that it was possible to write a Profile259 type provider today, so it would be good to have that validated.



> How to allow consumers to use arbitrary version of FSharp.Core.dll? (As I understand new The ProvidedTypes API is only for erasing TP)

Good, good question.  If you take a look a the ProvidedTypes ASK you will see how it finds the DLLs being referenced by the compiler (by a hack).  It then uses these to rewrite any references coming in via ``<@ ... @>`` quotations.  This is the right technique. However I don't know if this can be fully applied to quotations being used to specify generated code.


> I faced an error in VS2015 FSC : error FS2024: Static linking may not use assembly that targets different profile. that was fixed in VS2017 Microsoft/visualfsharp#99/ Does it mean that users of older version of VS may not be able to compile projects with SwaggerProvider?

Yes, I expect so.

> Should this approach work for 'all' platforms?

You mean Mono and .NET Core?  In theory yes, but both platforms would need to be fully tested

> Are there any other generative TP that already work everywhere?

No, I don't think there are any examples of generative cross-targeting type providers.

**Comment by sergey-tihon** [comment] 2017-04-03 21:03
Current status:

I am able to add NuGet package to  Profile259 PCL class library.
It installs correctly and IntelliSense work in VS2017, but when I build I see the error

> FSC: error FS2024: Static linking may not be used on an assembly referencing mscorlib (e.g. a .NET Framework assembly) when generating an assembly that references System.Runtime (e.g. a .NET Core or Portable assembly).

**Comment by sergey-tihon** [comment] 2017-04-04 15:06
@dsyme sure and even better - please try master branch of  https://github.com/sergey-tihon/generative-typeprovider-vnext this is minimal repro with very simple generative TP and tests

**Comment by sergey-tihon** [comment] 2019-11-06 19:14
Latest beta works in Xamarin! Proven!
<img width="1670" alt="Fullscreen_11_6_19__10_12_PM" src="https://user-images.githubusercontent.com/1197905/68329647-b9522a00-00e2-11ea-92ed-5a9b55226c3a.png">

**Closed by sergey-tihon** 2019-11-06 19:14 UTC
